### ISSUE TITLE
Making other deriving plugins work on 4.05

### ISSUE THREAD

**Issue by infinity0** [ocaml-ppx/ppx_deriving#143]
87050888d4fe8b12f667cfb91360e9292d344ec8 added 4.05 support but also changed the command-line interface of the ppx_deriving program so that plugin names need to be prefixed with an extra `-deriving-plugin` flag. This is causing build failures like mirleft/ocaml-nocrypto#122. I'm not sure how to tell the tooling to pass this flag in, but it seems like it should be done automatically by `ppx_deriving` rather than requiring everyone to edit their build scripts.

**Comment by gasche** [comment]
This should be fixed by #141 once it is merged.

**Comment by samoht** [comment]
Yes please :-)

**Comment by whitequark** [comment]
Triage: #141 merged but other derivers still broken, more work required.

**Comment by infinity0** [comment]
Part of the discussion there suggested that certain Jane Street packages need an update, I was able to build stuff using their development repo. @diml ?

**Comment by tuncer** [comment]
This affects me as well, and we're already in 4.06's beta cycle. Any predictions when this (and https://github.com/ocaml-ppx/ppx_deriving_yojson/issues/56) will be resolved?

**Comment by gasche** [comment]
We have a plan for a maintenance release of ppx-deriving 4.1, in the next few days, to support OCaml 4.05 and 4.06. Hopefully we can also do the same for ppx_deriving_yojson. So I would say that the current plan is to resolve this within the week. Sorry for the slow time working out the best short-term solution.

**Comment by tuncer** [comment]
@gasche, sounds good. If you don't mind, please keep us updated here.

**Comment by gasche** [comment]
Update: I have updates in the pipeline for ppx_deriving to support 4.05 and 4.06, and the plan is to make a maintenance release of ppx_deriving 4.2 first, and then release plugins on top of it (ppx_deriving_{hardcaml,protobuf,yojson}) which also have their 4.06-support PRs.

**Comment by tuncer** [comment]
@gasche, out of the various packages I install in each switch by default, `ulex` is the only one that's still 4.06-incompatible, and that has been fixed today (https://github.com/whitequark/ulex/commit/306f31f36b2104e2cf12eed7f4eccee2cdb11c51). But it's not released into opam yet.

Was I not supposed to be able to install `yojson`? It works for me.

**Comment by gasche** [comment]
ppx_deriving_yojson does not compile under 4.06 ( see pull request to fix this at https://github.com/ocaml-ppx/ppx_deriving_yojson/pull/66 ). You may be using just the `yojson` package, or another ppx-deriver for it.

**Comment by tuncer** [comment]
Right, it's just `yojson`.

**Comment by shonfeder** [comment]
I just switched to 4.06 to try this out. I think I must be doing something wrong, as trying to install ppx_deriving gives a constraint violation, and trying to pin ppx_deriving to 4.2.1 says that no such version exists:

```
$ opam switch show
4.06.0

$ opam --version
1.2.2

$ opam install ppx_deriving
[ERROR] ppx_deriving is not available because your system doesn't comply with ocaml-version > "4.03.0" & opam-version >= "1.2"
        & ocaml-version < "4.06.0".

$ opam install ppx_deriving 4.2.1
[ERROR] No package named 4 found.

$ opam pin add ppx_deriving 4.2.1
[ERROR] Package ppx_deriving has no version 4.2.1
```

**Comment by tuncer** [comment]
@shonfelder, it's still 4.2 (not 4.2.1) in the opam repo. Though to be clear, I wasn't installing `ppx_deriving` explicitly, and whatever else has been made compatible with 4.06 was enough for me to miss just `ulex`. Sorry, if my success report was misleading.

**Comment by tuncer** [comment]
@shonfeder, it's still 4.2 (not 4.2.1) in the opam repo. Though to be clear, I wasn't installing `ppx_deriving` explicitly, and whatever else has been made compatible with 4.06 was enough for me to miss just `ulex`. Sorry, if my success report was misleading.

**Comment by gasche** [comment]
No, 4.2.1 should be in the opam repo now, you should see it with `opam update`. @shonfeder the syntax is `opam install ppx_deriving.4.2.1`, not `ppx_deriving 4.2.1`, to force a specific version.

**Comment by shonfeder** [comment]
Ah! My mistake. Thanks, you @gasche, that worked for the installation.

**Comment by tuncer** [comment]
Confirmed it's visible in opam now.

**Comment by kit-ty-kate** [comment]
(this looks fixed so i closed it)
